database-user:
database-password:
database-url:

spring:
  profiles:
    active: "mem"
  datasource:
    url: ${database-url}
    username: ${database-user}
    password: ${database-password}
    driverClassName: org.h2.Driver
    initialize: true
    initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

flyway:
  user: ${database-user}
  password: ${database-password}
  schemas: public

---
spring:
  config:
    activate:
      on-profile: mem

database-user: sa
database-password: sa
database-url: jdbc:h2:mem:memdb

---
spring:
  config:
    activate:
      on-profile: file

database-user: sa
database-password: sa
database-url: jdbc:h2:file:~/database/filedb;AUTO_SERVER=TRUE